package com.zy.gis.pojo;

import java.io.Serializable;
/**
@description TODO 菜单信息
*/
public class MenuInfo implements Serializable {
    /**
     *
     * This field corresponds to the database column menu_info.id
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    private Integer id;

    /**
     * This field corresponds to the database column menu_info.name
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    private String name;

    /**
     *
     * This field corresponds to the database column menu_info.type
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    private Short type;

    /**
     *
     * This field corresponds to the database column menu_info.url
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    private String url;

    /**
     *
     * This field corresponds to the database column menu_info.tag
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    private String tag;

    /**
     *
     * This field corresponds to the database column menu_info.permission
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    private String permission;

    /**
     * 菜单等级
     */
    private Integer level;

    /**
     *
     * This field corresponds to the database column menu_info.sort
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.parent_id
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.create_time
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_info.update_time
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.id
     *
     * @return the value of menu_info.id
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.id
     *
     * @param id the value for menu_info.id
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.name
     *
     * @return the value of menu_info.name
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.name
     *
     * @param name the value for menu_info.name
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.type
     *
     * @return the value of menu_info.type
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.type
     *
     * @param type the value for menu_info.type
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.url
     *
     * @return the value of menu_info.url
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.url
     *
     * @param url the value for menu_info.url
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.tag
     *
     * @return the value of menu_info.tag
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.tag
     *
     * @param tag the value for menu_info.tag
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.permission
     *
     * @return the value of menu_info.permission
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method sets the value of the database column menu_info.permission
     *
     * @param permission the value for menu_info.permission
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method returns the value of the database column menu_info.sort
     *
     * @return the value of menu_info.sort
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.sort
     *
     * @param sort the value for menu_info.sort
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_info.parent_id
     *
     * @return the value of menu_info.parent_id
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_info.parent_id
     *
     * @param parentId the value for menu_info.parent_id
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method returns the value of the database column menu_info.create_time
     *
     * @return the value of menu_info.create_time
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method sets the value of the database column menu_info.create_time
     *
     * @param createTime the value for menu_info.create_time
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method returns the value of the database column menu_info.update_time
     *
     * @return the value of menu_info.update_time
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method sets the value of the database column menu_info.update_time
     *
     * @param updateTime the value for menu_info.update_time
     *
     * @mbg.generated Sat Oct 17 16:57:36 CST 2020
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    @Override
    public String toString() {
        return "MenuInfo{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", type=" + type +
                ", url='" + url + '\'' +
                ", tag='" + tag + '\'' +
                ", permission='" + permission + '\'' +
                ", level=" + level +
                ", sort=" + sort +
                ", parentId=" + parentId +
                ", createTime='" + createTime + '\'' +
                ", updateTime='" + updateTime + '\'' +
                '}';
    }
}