package com.zy.gis.pojo;

import java.io.Serializable;
import java.util.List;

public class OrganizeInfo extends BaseQueryEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize_info.id
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize_info.organize_name
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    private String organizeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize_info.node_level
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    private String nodeLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize_info.spread
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    private String spread;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize_info.disabled
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    private String disabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize_info.p_id
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    private String pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize_info.longitude
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize_info.latitude
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    private String latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize_info.create_time
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize_info.update_time
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    private String updateTime;

    /**
     * 20211102 Wangchong 保留字段,可以存储额外的信息
     * 例如"{"boxNo":"",...}"
     */
    private String reserveField;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize_info.id
     *
     * @return the value of organize_info.id
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize_info.id
     *
     * @param id the value for organize_info.id
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize_info.organize_name
     *
     * @return the value of organize_info.organize_name
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    public String getOrganizeName() {
        return organizeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize_info.organize_name
     *
     * @param organizeName the value for organize_info.organize_name
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    public void setOrganizeName(String organizeName) {
        this.organizeName = organizeName == null ? null : organizeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize_info.node_level
     *
     * @return the value of organize_info.node_level
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    public String getNodeLevel() {
        return nodeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize_info.node_level
     *
     * @param nodeLevel the value for organize_info.node_level
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    public void setNodeLevel(String nodeLevel) {
        this.nodeLevel = nodeLevel == null ? null : nodeLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize_info.spread
     *
     * @return the value of organize_info.spread
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    public String getSpread() {
        return spread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize_info.spread
     *
     * @param spread the value for organize_info.spread
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    public void setSpread(String spread) {
        this.spread = spread == null ? null : spread.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize_info.disabled
     *
     * @return the value of organize_info.disabled
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    public String getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize_info.disabled
     *
     * @param disabled the value for organize_info.disabled
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    public void setDisabled(String disabled) {
        this.disabled = disabled == null ? null : disabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize_info.p_id
     *
     * @return the value of organize_info.p_id
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    public String getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize_info.p_id
     *
     * @param pId the value for organize_info.p_id
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    public void setpId(String pId) {
        this.pId = pId == null ? null : pId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize_info.longitude
     *
     * @return the value of organize_info.longitude
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize_info.longitude
     *
     * @param longitude the value for organize_info.longitude
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize_info.latitude
     *
     * @return the value of organize_info.latitude
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize_info.latitude
     *
     * @param latitude the value for organize_info.latitude
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize_info.create_time
     *
     * @return the value of organize_info.create_time
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize_info.create_time
     *
     * @param createTime the value for organize_info.create_time
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize_info.update_time
     *
     * @return the value of organize_info.update_time
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize_info.update_time
     *
     * @param updateTime the value for organize_info.update_time
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    private List<OrganizeInfo> children;    //子节点数据
    private String state = "open";

    public List<OrganizeInfo> getChildren() {
        return children;
    }

    public void setChildren(List<OrganizeInfo> children) {
        this.children = children;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getReserveField() {
        return reserveField;
    }

    public void setReserveField(String reserveField) {
        this.reserveField = reserveField;
    }

    @Override
    public String toString() {
        return "OrganizeInfo{" +
                "id=" + id +
                ", organizeName='" + organizeName + '\'' +
                ", nodeLevel='" + nodeLevel + '\'' +
                ", spread='" + spread + '\'' +
                ", disabled='" + disabled + '\'' +
                ", pId='" + pId + '\'' +
                ", longitude='" + longitude + '\'' +
                ", latitude='" + latitude + '\'' +
                ", createTime='" + createTime + '\'' +
                ", updateTime='" + updateTime + '\'' +
                ", children=" + children +
                ", state='" + state + '\'' +
                '}';
    }
}