package com.zy.gis.mapper.devAndFacility;

import com.zy.gis.pojo.devAndFacility.DevControlPanelInfo;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface DevControlPanelInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_control_panel_info
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_control_panel_info
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    int insert(DevControlPanelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_control_panel_info
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    int insertSelective(DevControlPanelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_control_panel_info
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    DevControlPanelInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_control_panel_info
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    int updateByPrimaryKeySelective(DevControlPanelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_control_panel_info
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    int updateByPrimaryKey(DevControlPanelInfo record);
    /**
     * @Description:获取所有工控机设备数据
     * @author hhp
     * @date 2021/9/8 15:49
     * @param record:
     * @return {@link List< DevControlPanelInfo>}
     */
    List<DevControlPanelInfo> getAllDevControlPanelInfo(DevControlPanelInfo record);

    /**
     * @Description:获取所有工控机设备数量
     * @author hhp
     * @date 2021/9/8 15:49
     * @param record:
     * @return {@link int}
     */
    int getAllDevControlPanelCount(DevControlPanelInfo record);

    int updateDevControlPanelByBoxNo(DevControlPanelInfo record);

    /**
    @author Wangchong
    @date 2021/10/30 11:23
    @description TODO 查询所有繁易屏设备编号
    @return 设备编号
    */
    List<String> selectAllBoxNo();
}