package com.zy.gis.mapper.devAndFacility;

import com.zy.gis.pojo.devAndFacility.DevFlowMeterInfo;
import com.zy.gis.pojo.devAndFacility.DevInfo;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface DevFlowMeterInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_flow_meter_info
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_flow_meter_info
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    int insert(DevFlowMeterInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_flow_meter_info
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    int insertSelective(DevFlowMeterInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_flow_meter_info
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    DevFlowMeterInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_flow_meter_info
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    int updateByPrimaryKeySelective(DevFlowMeterInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_flow_meter_info
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    int updateByPrimaryKey(DevFlowMeterInfo record);

    int insertDev(DevInfo devInfo);

    List<DevInfo> getAllDev(DevInfo devInfo);

    int getAllDevCount(DevInfo devInfo);

    int updateDev(DevInfo devInfo);
}