package com.zy.gis.mapper.devAndFacility;

import com.zy.gis.pojo.devAndFacility.DevInfo;
import com.zy.gis.pojo.devAndFacility.DevRainMeterInfo;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface DevRainMeterInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_rain_meter_info
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_rain_meter_info
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    int insert(DevRainMeterInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_rain_meter_info
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    int insertSelective(DevRainMeterInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_rain_meter_info
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    DevRainMeterInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_rain_meter_info
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    int updateByPrimaryKeySelective(DevRainMeterInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_rain_meter_info
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    int updateByPrimaryKey(DevRainMeterInfo record);

    int insertDev(DevInfo devInfo);

    List<DevInfo> getAllDev(DevInfo devInfo);

    int getAllDevCount(DevInfo devInfo);

    int updateDev(DevInfo devInfo);
}