package com.zy.gis.mapper.devAndFacility;

import com.zy.gis.pojo.devAndFacility.DevTypeInfo;
import com.zy.gis.pojo.devAndFacility.NetworkPointTypeInfo;
import com.zy.gis.pojo.devAndFacility.SystemTypeInfo;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface DevTypeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_type_info
     *
     * @mbg.generated Thu Sep 02 10:53:46 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_type_info
     *
     * @mbg.generated Thu Sep 02 10:53:46 CST 2021
     */
    int insert(DevTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_type_info
     *
     * @mbg.generated Thu Sep 02 10:53:46 CST 2021
     */
    int insertSelective(DevTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_type_info
     *
     * @mbg.generated Thu Sep 02 10:53:46 CST 2021
     */
    DevTypeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_type_info
     *
     * @mbg.generated Thu Sep 02 10:53:46 CST 2021
     */
    int updateByPrimaryKeySelective(DevTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_type_info
     *
     * @mbg.generated Thu Sep 02 10:53:46 CST 2021
     */
    int updateByPrimaryKey(DevTypeInfo record);


    /**
     * @Description: 获取所有设备类型
     * @author hhp
     * @date 2021/9/2 17:58
     * @param devTypeInfo:
     * @return {@link List< DevTypeInfo>}
     */
    List<DevTypeInfo> getAllDevType(DevTypeInfo devTypeInfo);

    /**
     * @Description: 获取所有设备类型数量
     * @author hhp
     * @date 2021/9/2 17:58
     * @param devTypeInfo:
     * @return {@link int}
     */
    int getAllDevTypeCount(DevTypeInfo devTypeInfo);






}