package com.zy.gis.mapper.devAndFacility;

import com.zy.gis.pojo.devAndFacility.DevInfo;
import com.zy.gis.pojo.devAndFacility.DevWaterPumpInfo;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface DevWaterPumpInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_water_pump_info
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_water_pump_info
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    int insert(DevWaterPumpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_water_pump_info
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    int insertSelective(DevWaterPumpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_water_pump_info
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    DevWaterPumpInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_water_pump_info
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    int updateByPrimaryKeySelective(DevWaterPumpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_water_pump_info
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    int updateByPrimaryKey(DevWaterPumpInfo record);

    int insertDev(DevInfo devInfo);

    List<DevInfo> getAllDev(DevInfo devInfo);

    int getAllDevCount(DevInfo devInfo);

    int updateDev(DevInfo devInfo);
}