package com.zy.gis.mapper.devAndFacility;

import com.zy.gis.pojo.devAndFacility.MaterialTypeInfo;
import com.zy.gis.pojo.devAndFacility.NetworkPointTypeInfo;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface MaterialTypeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type_info
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type_info
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    int insert(MaterialTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type_info
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    int insertSelective(MaterialTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type_info
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    MaterialTypeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type_info
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    int updateByPrimaryKeySelective(MaterialTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_type_info
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    int updateByPrimaryKey(MaterialTypeInfo record);


    /**
     * @Description: 获取所有材质类型数据
     * @author hhp
     * @date 2021/9/4 16:17
     * @param materialTypeInfo:
     * @return {@link List< MaterialTypeInfo>}
     */
    List<MaterialTypeInfo> getAllMaterialType(MaterialTypeInfo materialTypeInfo);

    /**
     * @Description: 获取所有材质类型数量
     * @author hhp
     * @date 2021/9/4 16:17
     * @param materialTypeInfo:
     * @return {@link int}
     */
    int getAllMaterialTypeCount(MaterialTypeInfo materialTypeInfo);
}