package com.zy.gis.mapper.devAndFacility;

import com.zy.gis.pojo.devAndFacility.NetworkPointTypeInfo;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface NetworkPointTypeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_point_type_info
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_point_type_info
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    int insert(NetworkPointTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_point_type_info
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    int insertSelective(NetworkPointTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_point_type_info
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    NetworkPointTypeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_point_type_info
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    int updateByPrimaryKeySelective(NetworkPointTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network_point_type_info
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    int updateByPrimaryKey(NetworkPointTypeInfo record);

    /**
     * @Description: 获取所有管网点位类型数据
     * @author hhp
     * @date 2021/9/4 15:28
     * @param networkPointTypeInfo:
     * @return {@link List< NetworkPointTypeInfo>}
     */
    List<NetworkPointTypeInfo> getAllNetworkPointType(NetworkPointTypeInfo networkPointTypeInfo);


    /**
     * @Description: 获取所有管网点位类型数量
     * @author hhp
     * @date 2021/9/4 15:29
     * @param networkPointTypeInfo:
     * @return {@link int}
     */
    int getAllNetworkPointTypeCount(NetworkPointTypeInfo networkPointTypeInfo);
}