package com.zy.gis.mapper.devAndFacility;

import com.zy.gis.pojo.devAndFacility.MaterialTypeInfo;
import com.zy.gis.pojo.devAndFacility.SpecsTypeInfo;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SpecsTypeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table specs_type_info
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table specs_type_info
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    int insert(SpecsTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table specs_type_info
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    int insertSelective(SpecsTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table specs_type_info
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    SpecsTypeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table specs_type_info
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    int updateByPrimaryKeySelective(SpecsTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table specs_type_info
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    int updateByPrimaryKey(SpecsTypeInfo record);

    /**
     * @Description: 获取所有规格类型数据
     * @author hhp
     * @date 2021/9/4 16:18
     * @param record:
     * @return {@link List< SpecsTypeInfo>}
     */
    List<SpecsTypeInfo> getAllSpecsType(SpecsTypeInfo record);

    /**
     * @Description: 获取所有规格类型数量
     * @author hhp
     * @date 2021/9/4 16:19
     * @param record:
     * @return {@link int}
     */
    int getAllSpecsTypeCount(SpecsTypeInfo record);
}