package com.zy.gis.mapper.devAndFacility;

import com.zy.gis.pojo.devAndFacility.SpecsTypeInfo;
import com.zy.gis.pojo.devAndFacility.SystemTypeInfo;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SystemTypeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table control_system_type_info
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table control_system_type_info
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    int insert(SystemTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table control_system_type_info
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    int insertSelective(SystemTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table control_system_type_info
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    SystemTypeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table control_system_type_info
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    int updateByPrimaryKeySelective(SystemTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table control_system_type_info
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    int updateByPrimaryKey(SystemTypeInfo record);

    /**
     * @Description: 数据
     * @author hhp
     * @date 2021/9/4 16:20
     * @param record:
     * @return {@link List< SystemTypeInfo>}
     */
    List<SystemTypeInfo> getAllSystemType(SystemTypeInfo record);

    /**
     * @Description: 获取所有主控系统类型数量
     * @author hhp
     * @date 2021/9/4 16:20
     * @param record:
     * @return {@link int}
     */
    int getAllSystemTypeCount(SystemTypeInfo record);


    /**
     * @Description:根据系统类型名称获取系统类型数据
     * @param systemTypeName
     * @return
     */
    List<SystemTypeInfo> getDevTypeNameGroup(String systemTypeName);




}