server:
  port: 14001 #服务端口
#  ssl:
#    key-store: classpath:5369871_www.hzzy.tech.pfx  #SSL证书存放的位置
#    key-store-password: RCA03v3J   #密钥
#    key-store-type: PKCS12 #类型

#  my:
#    httpPort: 80
#    httpsPort: 443
  error:
    include-exception: true #显示异常信息
    include-message: always #一直显示

spring:
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/water_balance?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 200MB #最大请求文件的大小
      max-file-size: 200MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zy.gis.pojo
  configuration:
    map-underscore-to-camel-case: true #开启驼峰规则
#配置开启sql打印
logging:
  config:
  level:
    com.zy.gis.mapper: debug
    com.zy.gis.aop: debug
