package com.zy.gis.pojo.devAndFacility;

import com.zy.gis.pojo.BaseQueryEntity;

public class DevControlPanelInfo extends BaseQueryEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_control_panel_info.id
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_control_panel_info.box_no
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    private String boxNo;
    private String boxAlias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_control_panel_info.box_id
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    private String boxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_control_panel_info.box_state
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    private String boxState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_control_panel_info.facility_type
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    private String facilityType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_control_panel_info.facility_no
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    private String facilityNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_control_panel_info.dev_num
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    private Integer devNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_control_panel_info.useLongitude
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    private String uselongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_control_panel_info.useLatitude
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    private String uselatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_control_panel_info.radius
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    private String radius;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_control_panel_info.address
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_control_panel_info.longitude
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_control_panel_info.latitude
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    private String latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_control_panel_info.locationFetchType
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    private String locationfetchtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_control_panel_info.create_time
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_control_panel_info.update_time
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_control_panel_info.id
     *
     * @return the value of dev_control_panel_info.id
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_control_panel_info.id
     *
     * @param id the value for dev_control_panel_info.id
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_control_panel_info.box_no
     *
     * @return the value of dev_control_panel_info.box_no
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public String getBoxNo() {
        return boxNo;
    }

    public String getBoxAlias() {
        return boxAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_control_panel_info.box_no
     *
     * @param boxNo the value for dev_control_panel_info.box_no
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public void setBoxNo(String boxNo) {
        this.boxNo = boxNo == null ? null : boxNo.trim();
    }

    public void setBoxAlias(String boxAlias) {
        this.boxAlias = boxAlias == null ? null : boxAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_control_panel_info.box_id
     *
     * @return the value of dev_control_panel_info.box_id
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public String getBoxId() {
        return boxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_control_panel_info.box_id
     *
     * @param boxId the value for dev_control_panel_info.box_id
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public void setBoxId(String boxId) {
        this.boxId = boxId == null ? null : boxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_control_panel_info.box_state
     *
     * @return the value of dev_control_panel_info.box_state
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public String getBoxState() {
        return boxState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_control_panel_info.box_state
     *
     * @param boxState the value for dev_control_panel_info.box_state
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public void setBoxState(String boxState) {
        this.boxState = boxState == null ? null : boxState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_control_panel_info.facility_type
     *
     * @return the value of dev_control_panel_info.facility_type
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public String getFacilityType() {
        return facilityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_control_panel_info.facility_type
     *
     * @param facilityType the value for dev_control_panel_info.facility_type
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public void setFacilityType(String facilityType) {
        this.facilityType = facilityType == null ? null : facilityType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_control_panel_info.facility_no
     *
     * @return the value of dev_control_panel_info.facility_no
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public String getFacilityNo() {
        return facilityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_control_panel_info.facility_no
     *
     * @param facilityNo the value for dev_control_panel_info.facility_no
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public void setFacilityNo(String facilityNo) {
        this.facilityNo = facilityNo == null ? null : facilityNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_control_panel_info.dev_num
     *
     * @return the value of dev_control_panel_info.dev_num
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public Integer getDevNum() {
        return devNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_control_panel_info.dev_num
     *
     * @param devNum the value for dev_control_panel_info.dev_num
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public void setDevNum(Integer devNum) {
        this.devNum = devNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_control_panel_info.useLongitude
     *
     * @return the value of dev_control_panel_info.useLongitude
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public String getUselongitude() {
        return uselongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_control_panel_info.useLongitude
     *
     * @param uselongitude the value for dev_control_panel_info.useLongitude
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public void setUselongitude(String uselongitude) {
        this.uselongitude = uselongitude == null ? null : uselongitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_control_panel_info.useLatitude
     *
     * @return the value of dev_control_panel_info.useLatitude
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public String getUselatitude() {
        return uselatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_control_panel_info.useLatitude
     *
     * @param uselatitude the value for dev_control_panel_info.useLatitude
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public void setUselatitude(String uselatitude) {
        this.uselatitude = uselatitude == null ? null : uselatitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_control_panel_info.radius
     *
     * @return the value of dev_control_panel_info.radius
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public String getRadius() {
        return radius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_control_panel_info.radius
     *
     * @param radius the value for dev_control_panel_info.radius
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public void setRadius(String radius) {
        this.radius = radius == null ? null : radius.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_control_panel_info.address
     *
     * @return the value of dev_control_panel_info.address
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_control_panel_info.address
     *
     * @param address the value for dev_control_panel_info.address
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_control_panel_info.longitude
     *
     * @return the value of dev_control_panel_info.longitude
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_control_panel_info.longitude
     *
     * @param longitude the value for dev_control_panel_info.longitude
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_control_panel_info.latitude
     *
     * @return the value of dev_control_panel_info.latitude
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_control_panel_info.latitude
     *
     * @param latitude the value for dev_control_panel_info.latitude
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_control_panel_info.locationFetchType
     *
     * @return the value of dev_control_panel_info.locationFetchType
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public String getLocationfetchtype() {
        return locationfetchtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_control_panel_info.locationFetchType
     *
     * @param locationfetchtype the value for dev_control_panel_info.locationFetchType
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public void setLocationfetchtype(String locationfetchtype) {
        this.locationfetchtype = locationfetchtype == null ? null : locationfetchtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_control_panel_info.create_time
     *
     * @return the value of dev_control_panel_info.create_time
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_control_panel_info.create_time
     *
     * @param createTime the value for dev_control_panel_info.create_time
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_control_panel_info.update_time
     *
     * @return the value of dev_control_panel_info.update_time
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_control_panel_info.update_time
     *
     * @param updateTime the value for dev_control_panel_info.update_time
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    private String devType = "工控机";

    public String getDevType() {
        return devType;
    }

    public void setDevType(String devType) {
        this.devType = devType;
    }

    public String systemType;

    public String getSystemType() {
        return systemType;
    }

    public void setSystemType(String systemType) {
        this.systemType = systemType;
    }
}