package com.zy.gis.pojo.devAndFacility;

public class DevValveInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_valve_info.id
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_valve_info.devSN
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    private String devSN;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_valve_info.dev_model
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    private String devModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_valve_info.dev_factory
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    private String devFactory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_valve_info.dev_state
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    private String devState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_valve_info.facility_no
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    private String facilityNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_valve_info.box_no
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    private String boxNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_valve_info.create_time
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_valve_info.update_time
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_valve_info.id
     *
     * @return the value of dev_valve_info.id
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_valve_info.id
     *
     * @param id the value for dev_valve_info.id
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_valve_info.devSN
     *
     * @return the value of dev_valve_info.devSN
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public String getDevsn() {
        return devSN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_valve_info.devSN
     *
     * @param devSN the value for dev_valve_info.devSN
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public void setDevsn(String devSN) {
        this.devSN = devSN == null ? null : devSN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_valve_info.dev_model
     *
     * @return the value of dev_valve_info.dev_model
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public String getDevModel() {
        return devModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_valve_info.dev_model
     *
     * @param devModel the value for dev_valve_info.dev_model
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public void setDevModel(String devModel) {
        this.devModel = devModel == null ? null : devModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_valve_info.dev_factory
     *
     * @return the value of dev_valve_info.dev_factory
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public String getDevFactory() {
        return devFactory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_valve_info.dev_factory
     *
     * @param devFactory the value for dev_valve_info.dev_factory
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public void setDevFactory(String devFactory) {
        this.devFactory = devFactory == null ? null : devFactory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_valve_info.dev_state
     *
     * @return the value of dev_valve_info.dev_state
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public String getDevState() {
        return devState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_valve_info.dev_state
     *
     * @param devState the value for dev_valve_info.dev_state
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public void setDevState(String devState) {
        this.devState = devState == null ? null : devState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_valve_info.facility_no
     *
     * @return the value of dev_valve_info.facility_no
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public String getFacilityNo() {
        return facilityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_valve_info.facility_no
     *
     * @param facilityNo the value for dev_valve_info.facility_no
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public void setFacilityNo(String facilityNo) {
        this.facilityNo = facilityNo == null ? null : facilityNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_valve_info.box_no
     *
     * @return the value of dev_valve_info.box_no
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public String getBoxNo() {
        return boxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_valve_info.box_no
     *
     * @param boxNo the value for dev_valve_info.box_no
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public void setBoxNo(String boxNo) {
        this.boxNo = boxNo == null ? null : boxNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_valve_info.create_time
     *
     * @return the value of dev_valve_info.create_time
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_valve_info.create_time
     *
     * @param createTime the value for dev_valve_info.create_time
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_valve_info.update_time
     *
     * @return the value of dev_valve_info.update_time
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_valve_info.update_time
     *
     * @param updateTime the value for dev_valve_info.update_time
     *
     * @mbg.generated Wed Sep 08 16:35:59 CST 2021
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}