package com.zy.gis.pojo.devAndFacility;

import com.zy.gis.pojo.BaseQueryEntity;

public class MaterialTypeInfo extends BaseQueryEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_type_info.id
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_type_info.material_type_name
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    private String materialTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_type_info.create_time
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_type_info.update_time
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_type_info.id
     *
     * @return the value of material_type_info.id
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_type_info.id
     *
     * @param id the value for material_type_info.id
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_type_info.material_type_name
     *
     * @return the value of material_type_info.material_type_name
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    public String getMaterialTypeName() {
        return materialTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_type_info.material_type_name
     *
     * @param materialTypeName the value for material_type_info.material_type_name
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    public void setMaterialTypeName(String materialTypeName) {
        this.materialTypeName = materialTypeName == null ? null : materialTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_type_info.create_time
     *
     * @return the value of material_type_info.create_time
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_type_info.create_time
     *
     * @param createTime the value for material_type_info.create_time
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_type_info.update_time
     *
     * @return the value of material_type_info.update_time
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_type_info.update_time
     *
     * @param updateTime the value for material_type_info.update_time
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}