package com.zy.gis.pojo.devAndFacility;

import com.zy.gis.pojo.BaseQueryEntity;

public class NetworkPointTypeInfo extends BaseQueryEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column network_point_type_info.id
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column network_point_type_info.point_type_name
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    private String pointTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column network_point_type_info.create_time
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column network_point_type_info.update_time
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column network_point_type_info.id
     *
     * @return the value of network_point_type_info.id
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column network_point_type_info.id
     *
     * @param id the value for network_point_type_info.id
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column network_point_type_info.point_type_name
     *
     * @return the value of network_point_type_info.point_type_name
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    public String getPointTypeName() {
        return pointTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column network_point_type_info.point_type_name
     *
     * @param pointTypeName the value for network_point_type_info.point_type_name
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    public void setPointTypeName(String pointTypeName) {
        this.pointTypeName = pointTypeName == null ? null : pointTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column network_point_type_info.create_time
     *
     * @return the value of network_point_type_info.create_time
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column network_point_type_info.create_time
     *
     * @param createTime the value for network_point_type_info.create_time
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column network_point_type_info.update_time
     *
     * @return the value of network_point_type_info.update_time
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column network_point_type_info.update_time
     *
     * @param updateTime the value for network_point_type_info.update_time
     *
     * @mbg.generated Sat Sep 04 15:15:47 CST 2021
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}