package com.zy.gis.mapper;

import com.zy.gis.pojo.OrganizeInfo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface OrganizeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize_info
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize_info
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    int insert(OrganizeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize_info
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    int insertSelective(OrganizeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize_info
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    OrganizeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize_info
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    int updateByPrimaryKeySelective(OrganizeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize_info
     *
     * @mbg.generated Thu Sep 02 10:51:02 CST 2021
     */
    int updateByPrimaryKey(OrganizeInfo record);

    /**
     * @Description: 查询子节点
     * @author hhp
     * @date 2021/9/1 14:38
     * @param pId: 父节点ID
     * @return {@link List< OrganizeInfo>}
     */
    List<OrganizeInfo> queryChildrenOrganize(@Param("pId") String pId);

    /**
     * @Description: 获取所有组织信息
     * @author hhp
     * @date 2021/9/2 19:54
     * @param organizeInfo:
     * @return {@link List< OrganizeInfo>}
     */
    List<OrganizeInfo> getAllOrganize(OrganizeInfo organizeInfo);
}