package com.zy.gis.mapper;

import com.zy.gis.pojo.UserInfo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Aug 20 11:40:34 CST 2021
     */
    Integer deleteByPrimaryKey(@Param("userId") Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Aug 20 11:40:34 CST 2021
     */
    Integer insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Aug 20 11:40:34 CST 2021
     */
    Integer insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Aug 20 11:40:34 CST 2021
     */
    UserInfo selectByPrimaryKey(Integer userId);

    /**
     * 根据用户名称查询用户信息
     * @date 202108201155
     * @author Wangchong
     * @param userName 用户名称
     * @return 用户信息
     */
    UserInfo getUserInfoByUserName(@Param("userName")String userName);

    /**
     * 条件查询用户信息
     * @date 202108201701
     * @author Wangchong
     * @param userInfo 用户信息查询条件
     * @return 用户信息
     */
    List<UserInfo> getUserInfoList(UserInfo userInfo);

    /**
     * 条件查询用户信息数量
     * @date 202108201705
     * @author Wangchong
     * @param userInfo 用户信息查询条件
     * @return 用户信息记录条数
     */
    Integer getUserInfoListCount(UserInfo userInfo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Fri Aug 20 11:40:34 CST 2021
     */
    Integer updateByPrimaryKeySelective(UserInfo record);

}